backendOptions:
  # 需修改成项目subconverter后端部署地址
  - value: "http://sonicming.top:58081/sub?"
  - value: "http://103.101.205.136:58081/sub?"
  - value: "http://47.108.53.77:4581/sub?"
remoteConfig:
  # 本项目自定义配置
  - label: "sonic"
    options:
    - label: "sonic-zsokami_v2"
      value: "https://raw.githubusercontent.com/sonicmingit/clashRules/main/subConfig/zsokami-sonic.v2.ini"
    - label: "sonic-zsokami_v1"
      value: "https://raw.githubusercontent.com/sonicmingit/clashRules/main/subConfig/zsokami-sonic.v1.ini"
    - label: "sonic-group-pro"
      value: "https://raw.githubusercontent.com/sonicmingit/clashRules/main/subConfig/sonic-group-pro.ini"
    - label: "ACL4SSR_Online_Full"
      value: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full.ini"
  # 其他配置
  - label: "zsokami"
    options:
    - label: "ACL4SSR_Online 默认版 分组比较全 (与Github同步)"
      value: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online.ini"
    - label: "ACL4SSR_Online_AdblockPlus 更多去广告 (与Github同步)"
      value: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_AdblockPlus.ini"
    - label: "ACL4SSR_Online_NoAuto 无自动测速 (与Github同步)"
      value: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_NoAuto.ini"
    - label: "ACL4SSR_Online_NoReject 无广告拦截规则 (与Github同步)"
      value: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_NoReject.ini"
    - label: "ACL4SSR_Online_Mini 精简版 (与Github同步)"
      value: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini.ini"
    - label: "ACL4SSR_Online_Mini_AdblockPlus.ini 精简版 更多去广告 (与Github同步)"
      value: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini_AdblockPlus.ini"
    - label: "ACL4SSR_Online_Mini_NoAuto.ini 精简版 不带自动测速 (与Github同步)"
      value: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini_NoAuto.ini"
    - label: "ACL4SSR_Online_Mini_Fallback.ini 精简版 带故障转移 (与Github同步)"
      value: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini_Fallback.ini"
    - label: "ACL4SSR_Online_Mini_MultiMode.ini 精简版 自动测速、故障转移、负载均衡 (与Github同步)"
      value: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini_MultiMode.ini"
    - label: "ACL4SSR_Online_Full 全分组 重度用户使用 (与Github同步)"
      value: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full.ini"
    - label: "ACL4SSR_Online_Full_NoAuto.ini 全分组 无自动测速 重度用户使用 (与Github同步)"
      value: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_NoAuto.ini"
    - label: "ACL4SSR_Online_Full_AdblockPlus 全分组 重度用户使用 更多去广告 (与Github同步)"
      value: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_AdblockPlus.ini"
    - label: "ACL4SSR_Online_Full_Netflix 全分组 重度用户使用 奈飞全量 (与Github同步)"
      value: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_Netflix.ini"
  - label: "universal"
    options:
      - label: "No-Urltest"
        value: "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/remote-config/universal/no-urltest.ini"
      - label: "Urltest"
        value: "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/remote-config/universal/urltest.ini"
  - label: "customized"
    options:
      - label: "Maying"
        value: "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/remote-config/customized/maying.ini"
      - label: "Ytoo"
        value: "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/remote-config/customized/ytoo.ini"
      - label: "FlowerCloud"
        value: "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/remote-config/customized/flowercloud.ini"
      - label: "Nexitally"
        value: "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/remote-config/customized/nexitally.ini"
      - label: "SoCloud"
        value: "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/remote-config/customized/socloud.ini"
      - label: "ARK"
        value: "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/remote-config/customized/ark.ini"
      - label: "ssrCloud"
        value: "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/remote-config/customized/ssrcloud.ini"
  - label: "Special"
    options:
      - label: "NeteaseUnblock(仅规则，No-Urltest)"
        value: "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/remote-config/special/netease.ini"
      - label: "Basic(仅GEOIP CN + Final)"
        value: "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/remote-config/special/basic.ini"