# 国外的走国外，其他走国内，如果失败国内走单独seq，国外用mos解析，sock5走clash
log:
  level: debug
  file: "/tmp/mosdns.log"
# include 的插件会比本配置文件中的插件先初始化。
include: []
# API 入口设置
api:
  http: ":8888" # 在该地址启动 api 接口。
plugins:
  ## 国内域名 ##
  - tag: geosite_cn
    type: domain_set
    args:
      exps: # 域名表达式。
        - "lan"
        - "local"
        - "arpa"
        - "google.com"
      files:
        - "/etc/mosdns/rule/whitelist.txt"
        - "/var/mosdns/geosite_cn.txt"
        # 此两行注释,否则无法启动mosdns,原因为Geoip和Geosite两个文件UNPACK后无上述两文件。
        #- "/var/mosdns/geosite_apple-cn.txt"
        #- "/var/mosdns/geosite_category-games@cn.txt"
  ## 国内 IP ##
  - tag: geoip_cn
    type: ip_set
    args:
      ips: # 可以是 IP 或 CIDR。
        - "1.1.1.1"
        - "1.1.1.1/24"
      files:
        - "/var/mosdns/geoip_cn.txt"

  ## 国外域名 ##
  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/greylist.txt"
        - "/var/mosdns/geosite_geolocation-!cn.txt"

  ## 自定义hosts ##
  - tag: hosts
    type: hosts
    args:
      files:
        - "/etc/mosdns/rule/hosts.txt"

  ## 国内解析 ##
  - tag: local_forward
    type: forward
    args:
      concurrent: 3
      upstreams:
        - tag: unicom1
          addr: "221.11.1.68"
          enable_pipeline: true
          idle_timeout: 10
        - tag: unicom2
          addr: "124.89.1.129"
          enable_pipeline: true
        - tag: ali
          addr: "223.5.5.5"
          enable_pipeline: true
        - tag: ten
          addr: "119.29.29.29"
          enable_pipeline: true
        - tag: v6
          addr: "2400:3200::1"
          enable_pipeline: true
        # - tag: localdns
          # addr: "127.0.0.1:533"
          # enable_pipeline: true
          # idle_timeout: 3

  ## 国内解析 ##
  - tag: local_sequence
    type: sequence
    args:
      # 所有请求都优先返回 ipv4，屏蔽 ipv6。
      #- exec: prefer_ipv4
       #国内解析DNS
      - exec: $local_forward
      - matches:
       #  检查是否已经收到了DNS响应
        - has_resp
        # 局域网IP段
        - resp_ip 10.0.0.0/23
        exec: ttl 1800-0
      # 打印请求日志
      #- exec: query_summary local_sequence


  ## 国外解析 ##
  - tag: remote_sequence
    type: sequence
    args:
      # 规则
      - matches:
        # 检查查询类型是否为28（即IPv6地址查询）
        - qtype 28
        # 上述规则拒绝查询，0拒绝响应
        exec: reject 0
      # openclash 端口
      - exec: forward 127.0.0.1:7874
      - exec: ttl 1800-0
      # 打印请求日志
      #- exec: query_summary remote_sequence

  # 有响应终止返回
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: has_resp
        exec: accept
        # 打印请求日志
      #- exec: query_summary has_resp_sequence

  # fallback 本地查询
  - tag: fallback_local_forward
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "https://doh.apad.pro/dns-query"
          bootstrap: "218.2.2.2"
          enable_http3: false
  - tag: fallback_local
    type: sequence
    args:
      # fallback优先ipv4
      - exec: prefer_ipv4
      - exec: $fallback_local_forward
      # 输出日志
      - exec: query_summary fallback_local

  # fallback 外网mos查询走代理
  - tag: fallback_remote_forward
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "https://162.159.36.1/dns-query"
          enable_http3: false
          socks5: "127.0.0.1:7891" # 解析后走clash代理
        - addr: "https://162.159.46.1/dns-query"
          enable_http3: false
          socks5: "127.0.0.1:7891" # 解析后走clash代理
  - tag: fallback_remote
    type: sequence
    args:
      # fallback优先ipv4
      - exec: prefer_ipv4
      - exec: $fallback_remote_forward
      # 输出日志
      - exec: query_summary fallback_remote

  # fallback 用远程服务器 sequence
  - tag: fallback
    # 备用类型
    type: fallback
    args:
      # 主要序列 国内备用
      primary: fallback_local
      # 次要序列 国外解析
      secondary: fallback_remote
      # 阈值，主序列响应时间，默认200，增加到500
      threshold: 500
      # 表示次要序列始终待命，即使主要序列有效也可能使用次要序列。
      always_standby: true


  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，否则 sequence 找不到对应插件。
  # 顺序执行，解析成功后 jump has_resp_sequence 结束，不再进行后面解析
  - tag: main_sequence
    type: sequence
    args:
      ### --- hosts --- ###
      - exec: $hosts
      - exec: jump has_resp_sequence
      ### --- 拒绝类型为65（HTTPS DNS查询）的请求。 --- ###
      - matches:
        - qtype 65 # HTTPS DNS查询
        exec: reject 3
      ### --- 对类型为12（PTR记录，反向DNS查询）的请求执行国内解析序列。 --- ###
      - matches:
        - qtype 12
        exec: $local_sequence
      - exec: jump has_resp_sequence
      ### --- 国内外IP规则解析 --- ###
      # 优先匹配国外域名，如果匹配失败则执行国内解析序列。
      ## 国外解析 如果查询名匹配非国内域名集（geosite_no_cn），则执行国外解析序列。
      - matches:
        - qname $geosite_no_cn
        exec: $remote_sequence
      - exec: jump has_resp_sequence
      ## 国内解析 如果查询名匹配国内域名集（geosite_cn），则执行国内解析序列。
      # 匹配国内域名才走国内解析
#      - matches:
#        - qname $geosite_cn
#        exec: $local_sequence
      # 非国外都执行国内匹配
      - exec: $local_sequence
      - exec: jump has_resp_sequence
      ### --- 以上失败处理 --- ###
      - exec: $fallback



  # mosdns参数
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      # mosdns监听端口，后续在Adguard中作为上游地址填写。
      listen: ":5335"